# src/web/app.py
import sys
from pathlib import Path
# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import streamlit as st
import torch
from src.models.image_caption_model import ImageCaptionModel
from src.utils.image_utils import load_and_preprocess_image
from transformers import GPT2TokenizerFast
from PIL import Image
import os

st.set_page_config(page_title="Image Caption Generator", layout="centered")

st.title("🖼️ Image Caption Generator")
st.write("Upload an image and get a caption generated by the BLIP‑Encoder + GPT‑2 Decoder model.")

@st.cache_resource
def load_model():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = ImageCaptionModel().to(device)
    # Try to load latest checkpoint
    checkpoint_dir = "checkpoints"
    if os.path.isdir(checkpoint_dir):
        checkpoints = [f for f in os.listdir(checkpoint_dir) if f.endswith('.pt')]
        if checkpoints:
            latest = sorted(checkpoints)[-1]
            checkpoint_path = os.path.join(checkpoint_dir, latest)
            try:
                checkpoint = torch.load(checkpoint_path, map_location=device)
                model.load_state_dict(checkpoint['model_state_dict'])
                st.success(f"Loaded checkpoint: {latest}")
            except Exception as e:
                st.warning(f"Failed to load checkpoint: {e}")
    model.eval()
    return model, device

@st.cache_resource
def load_tokenizer():
    tokenizer = GPT2TokenizerFast.from_pretrained('gpt2')
    tokenizer.pad_token = tokenizer.eos_token
    return tokenizer

def generate_caption(model, tokenizer, image_tensor, device, max_length=30, temperature=1.0):
    model.eval()
    with torch.no_grad():
        prefix = model.encode_image(image_tensor.to(device))
        generated = torch.full((1, 1), tokenizer.eos_token_id, dtype=torch.long, device=device)
        for _ in range(max_length):
            token_embeds = model.decoder.transformer.wte(generated)
            inputs_embeds = torch.cat([prefix, token_embeds], dim=1)
            outputs = model.decoder.transformer(inputs_embeds=inputs_embeds)
            logits = model.decoder.lm_head(outputs.last_hidden_state)
            next_token_logits = logits[:, -1, :] / temperature
            probs = torch.softmax(next_token_logits, dim=-1)
            next_token = torch.multinomial(probs, num_samples=1)
            generated = torch.cat([generated, next_token], dim=1)
            if next_token.item() == tokenizer.eos_token_id:
                break
        generated_ids = generated[0, 1:].tolist()
        caption = tokenizer.decode(generated_ids, skip_special_tokens=True)
        return caption

model, device = load_model()
tokenizer = load_tokenizer()

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])
if uploaded_file is not None:
    image = Image.open(uploaded_file).convert('RGB')
    st.image(image, caption='Uploaded Image', use_column_width=True)
    # Preprocess
    image_tensor = load_and_preprocess_image(image)  # (1, C, H, W)
    # Generate
    with st.spinner('Generating caption...'):
        caption = generate_caption(model, tokenizer, image_tensor, device,
                                   max_length=st.slider("Max length", 5, 50, 20),
                                   temperature=st.slider("Temperature", 0.1, 2.0, 1.0, 0.1))
    st.success("Caption:")
    st.write(f"**{caption}**")
else:
    st.info("Please upload an image to get a caption.")